spring:
  profiles.active: ${SPRING_ACTIVE_PROFILE}
server:
  servlet.session.persistent: false

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

---

spring:
  profiles: dev
  h2.console.enabled: true
  datasource.url: jdbc:h2:mem:/.MyBooks
  jpa:
    hibernate.ddl-auto: create
  #jpa:
    #show-sql: true
    #properties.hibernate.format_sql: true

dataLoader:
  populate: true
  fromLine: 0

---

spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/mybooks
    username: ENC(+2z5W6bphNMgstRafjkgT4zJKiqnBsa1)
    password: ENC(IKjfPut1SBzf3wHKcPNt0x2ZAxtcBUtT)
    driverClassName: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate.ddl-auto: update

---

spring:
  profiles: heroku
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver
    initialization-mode: never
  jpa:
    hibernate.ddl-auto: ${SPRING_JPA_HIBERNATE_DDL-AUTO}
    #database-platform: ${SPRING_JPA_DATABASE-PLATFORM}

---

spring:
  profiles: heroku-demo
  h2.console.enabled: true
  datasource.url: jdbc:h2:mem:/.MyBooks
  jpa:
    hibernate.ddl-auto: create

dataLoader:
  populate: true
  fromLine: 0
  toLine: 100